// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: internal.proto

package internal

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Dial struct {
	ID                   *int64   `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Token                *string  `protobuf:"bytes,2,opt,name=Token" json:"Token,omitempty"`
	Name                 *string  `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Status               *float64 `protobuf:"fixed64,4,opt,name=Status" json:"Status,omitempty"`
	ModifiedTime         *int64   `protobuf:"varint,5,opt,name=ModifiedTime" json:"ModifiedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dial) Reset()         { *m = Dial{} }
func (m *Dial) String() string { return proto.CompactTextString(m) }
func (*Dial) ProtoMessage()    {}
func (*Dial) Descriptor() ([]byte, []int) {
	return fileDescriptor_internal_d4c4448ab679c3ee, []int{0}
}
func (m *Dial) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dial.Unmarshal(m, b)
}
func (m *Dial) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dial.Marshal(b, m, deterministic)
}
func (dst *Dial) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dial.Merge(dst, src)
}
func (m *Dial) XXX_Size() int {
	return xxx_messageInfo_Dial.Size(m)
}
func (m *Dial) XXX_DiscardUnknown() {
	xxx_messageInfo_Dial.DiscardUnknown(m)
}

var xxx_messageInfo_Dial proto.InternalMessageInfo

func (m *Dial) GetID() int64 {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return 0
}

func (m *Dial) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *Dial) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Dial) GetStatus() float64 {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return 0
}

func (m *Dial) GetModifiedTime() int64 {
	if m != nil && m.ModifiedTime != nil {
		return *m.ModifiedTime
	}
	return 0
}

func init() {
	proto.RegisterType((*Dial)(nil), "internal.Dial")
}

func init() { proto.RegisterFile("internal.proto", fileDescriptor_internal_d4c4448ab679c3ee) }

var fileDescriptor_internal_d4c4448ab679c3ee = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0xcc, 0x2b, 0x49,
	0x2d, 0xca, 0x4b, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x6a,
	0xb8, 0x58, 0x5c, 0x32, 0x13, 0x73, 0x84, 0xf8, 0xb8, 0x98, 0x3c, 0x5d, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x98, 0x83, 0x98, 0x3c, 0x5d, 0x84, 0x44, 0xb8, 0x58, 0x43, 0xf2, 0xb3, 0x53, 0xf3, 0x24,
	0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x21, 0x21, 0x2e, 0x16, 0xbf, 0xc4, 0xdc, 0x54,
	0x09, 0x66, 0xb0, 0x20, 0x98, 0x2d, 0x24, 0xc6, 0xc5, 0x16, 0x5c, 0x92, 0x58, 0x52, 0x5a, 0x2c,
	0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x18, 0x04, 0xe5, 0x09, 0x29, 0x71, 0xf1, 0xf8, 0xe6, 0xa7, 0x64,
	0xa6, 0x65, 0xa6, 0xa6, 0x84, 0x64, 0xe6, 0xa6, 0x4a, 0xb0, 0x82, 0xcd, 0x46, 0x11, 0x03, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x82, 0x73, 0xc3, 0x2b, 0x98, 0x00, 0x00, 0x00,
}
